# Generated by Django 5.0.7 on 2024-08-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options_alter_news_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.TextField(blank=True, verbose_name='Пользователь'),
        ),
    ]
